import { useEffect, useState } from 'react'
import { KeyRound, Plus, Trash2 } from 'lucide-react'
import { credentialsApi } from '../api/credentials'
import { devicesApi } from '../api/devices'
import type { Device, NetworkCredential, NetworkCredentialType } from '../types/api'
import { formatLocalDateTime } from '../utils/format'

export function CredentialsPage() {
  const [items, setItems] = useState<NetworkCredential[]>([]); const [devices, setDevices] = useState<Device[]>([]); const [name, setName] = useState(''); const [type, setType] = useState<NetworkCredentialType>('SnmpV2Community'); const [username, setUsername] = useState(''); const [secret, setSecret] = useState(''); const [deviceId, setDeviceId] = useState(''); const [error, setError] = useState<string | null>(null)
  const load = () => Promise.all([credentialsApi.list(), devicesApi.list()]).then(([nextItems, nextDevices]) => { setItems(nextItems); setDevices(nextDevices) }).catch((loadError) => setError(loadError instanceof Error ? loadError.message : 'Credentials unavailable.'))
  useEffect(() => { void load() }, [])
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(null); try { await credentialsApi.create({ name, type, username: type === 'SshPassword' ? username : null, secret, deviceId: deviceId ? Number(deviceId) : null }); setSecret(''); setName(''); setUsername(''); await load() } catch (saveError) { setSecret(''); setError(saveError instanceof Error ? saveError.message : 'Credential could not be saved.') } }
  return <div className="page"><header className="page-header"><div><span className="eyebrow">Security settings</span><h1>Network Credentials</h1><p>Store encrypted SNMP communities and SSH passwords. Saved secrets can never be read back by the browser.</p></div></header>{error && <div className="form-error">{error}</div>}<section className="panel credential-create-panel"><header className="panel-header"><div><h2>Add credential</h2><p>The secret is encrypted before database persistence.</p></div><KeyRound size={20} /></header><form onSubmit={submit}><label>Name<input value={name} onChange={(e) => setName(e.target.value)} required maxLength={100} /></label><label>Type<select value={type} onChange={(e) => setType(e.target.value as NetworkCredentialType)}><option value="SnmpV2Community">SNMP v2c community</option><option value="SshPassword">SSH password</option></select></label>{type === 'SshPassword' && <label>Username<input value={username} onChange={(e) => setUsername(e.target.value)} required /></label>}<label>Secret<input type="password" value={secret} onChange={(e) => setSecret(e.target.value)} required autoComplete="new-password" /></label><label>Device (optional)<select value={deviceId} onChange={(e) => setDeviceId(e.target.value)}><option value="">Shared credential</option>{devices.map((device) => <option key={device.id} value={device.id}>{device.name}</option>)}</select></label><button className="button primary"><Plus size={15} /> Save credential</button></form></section><section className="panel"><header className="panel-header"><div><h2>Saved credentials</h2><p>Metadata only. Encrypted and plaintext secret values are never returned.</p></div></header><div className="table-scroll"><table className="data-table credentials-table"><thead><tr><th>Name</th><th>Type</th><th>Username</th><th>Device</th><th>Updated</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.type}</td><td>{item.username ?? '—'}</td><td>{devices.find((device) => device.id === item.deviceId)?.name ?? 'Shared'}</td><td>{formatLocalDateTime(item.updatedAt)}</td><td><button className="icon-button danger" title="Delete credential" onClick={() => void credentialsApi.remove(item.id).then(load)}><Trash2 size={14} /></button></td></tr>)}</tbody></table></div></section></div>
}
